### ISSUE TITLE
PlainABC fails on inheritance with abstract methods only

### ISSUE THREAD

**Issue by tokarenko** [ChieloNewctle/plain-abc#7]
I am unable to use inheritance with PlainABC to extend base class with more abstract methods. The same works fine with ABC.

```
from abc import abstractmethod
from typing import Literal

from plain_abc import PlainABC 


class IMediaType(PlainABC):
    pass


class IApplicationPython(IMediaType):
    
    @property
    @abstractmethod
    def media_type(self) -> Literal["application/prs.binary+python"]:
        ...


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dstokar3/panda/.venv/lib/python3.11/site-packages/plain_abc.py", line 133, in __init_subclass__
    raise MissingImplError(cls, missing)
plain_abc.MissingImplError: missing implementation in <class '__main__.IApplicationPython'> for media_type
```

**Comment by ChieloNewctle** [comment]
To extend an abstract class **as another abstract class**, `PlainABC` is required to be one of the bases.

I will document this in `README.md`.

For example:
```python
from abc import abstractmethod
from typing import Literal

from plain_abc import PlainABC 


class IMediaType(PlainABC):
    pass


class IApplicationPython(IMediaType, PlainABC):
    
    @property
    @abstractmethod
    def media_type(self) -> Literal["application/prs.binary+python"]:
        ...
```
